version: '3.0'

services:
  projects:
    container_name: projects
    build: 
      context: .
      dockerfile: ./apps/project/Dockerfile
    env_file: 
      - .development.env    
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - 5000:5000      
    command: npm run start:dev
    depends_on:
      - postgres
      - rabbitmq
      - auth
    restart: always

  auth:
    container_name: auth
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file: 
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules

      
    command: npm run start:dev auth
    
    depends_on:
      - rabbitmq
      - postgres
    restart: always
  
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # RabbitMQ Port
  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data 
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
